<?php
/**
 * Plugin Name: Jewelry Image Optimization
 * Description: WebP conversion, JPEG quality control, EXIF stripping, lazy loading optimization
 * Version: 2.0
 * Author: Jewelry Miami
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/* =========================================================================
 * UPLOAD OPTIMIZATION — WebP, Quality, EXIF, Resize
 * ========================================================================= */

/**
 * Convert uploaded JPEG/PNG thumbnails to WebP format.
 * WordPress 5.8+ generates sub-sizes; this filter tells the image editor
 * to output WebP instead of the original format for every generated sub-size.
 *
 * The original uploaded file stays as-is (JPEG/PNG) for compatibility,
 * but all generated thumbnails (150, 300, 600, 768, 1024, 1536, 2048) get WebP.
 */
add_filter( 'image_editor_output_format', 'jewelry_webp_output_format' );
function jewelry_webp_output_format( $formats ) {
    $formats['image/jpeg'] = 'image/webp';
    $formats['image/png']  = 'image/webp';
    return $formats;
}

/**
 * Set JPEG compression quality to 85.
 * Default WordPress is 82. For jewelry, 85 preserves sparkle/detail in gold and gems.
 * This applies to JPEG sub-sizes and any JPEG manipulation by WP_Image_Editor.
 */
add_filter( 'wp_editor_set_quality', 'jewelry_image_quality', 10, 2 );
function jewelry_image_quality( $quality, $mime_type = 'image/jpeg' ) {
    if ( 'image/jpeg' === $mime_type || 'image/jpg' === $mime_type ) {
        return 85;
    }
    // WebP quality — slightly lower since WebP is more efficient.
    if ( 'image/webp' === $mime_type ) {
        return 82;
    }
    return $quality;
}

/**
 * Reduce the big image size threshold from 2560px to 1600px.
 * For jewelry e-commerce, 1600px is more than enough for the largest display.
 * This auto-scales any upload wider/taller than 1600px down to 1600px.
 */
add_filter( 'big_image_size_threshold', 'jewelry_big_image_threshold' );
function jewelry_big_image_threshold() {
    return 1600;
}

/**
 * Strip EXIF metadata from uploaded images for privacy and file size.
 *
 * Hooks into wp_generate_attachment_metadata (runs after upload + thumbnail generation).
 * Uses Imagick to strip profiles (EXIF, IPTC, ICC) from the original uploaded file.
 * Sub-sizes generated by WP don't carry EXIF by default, but we strip the original.
 */
add_filter( 'wp_generate_attachment_metadata', 'jewelry_strip_exif_on_upload', 10, 2 );
function jewelry_strip_exif_on_upload( $metadata, $attachment_id ) {
    $file = get_attached_file( $attachment_id );
    if ( ! $file || ! file_exists( $file ) ) {
        return $metadata;
    }

    $mime = get_post_mime_type( $attachment_id );
    if ( ! in_array( $mime, array( 'image/jpeg', 'image/jpg', 'image/png' ), true ) ) {
        return $metadata;
    }

    // Use Imagick if available (preferred — faster, lossless strip).
    if ( class_exists( 'Imagick' ) ) {
        try {
            $img = new Imagick( $file );
            $img->stripImage(); // Removes EXIF, IPTC, ICC profiles.
            $img->writeImage( $file );
            $img->destroy();
        } catch ( Exception $e ) {
            error_log( 'Jewelry EXIF strip failed: ' . $e->getMessage() );
        }
    }

    return $metadata;
}

/**
 * Increase the omit lazy loading threshold.
 * WordPress skips lazy loading for the first N images.
 * Default is ~3, we bump to 8 so collection images above-fold load eagerly.
 */
add_filter( 'wp_omit_loading_attr_threshold', function() {
    return 8;
});

/**
 * Preload critical above-the-fold images on the home page.
 * This tells the browser to download these ASAP without waiting for HTML parsing.
 */
add_action( 'wp_head', 'jewelry_preload_critical_images', 1 );
function jewelry_preload_critical_images() {
    if ( ! is_front_page() ) {
        return;
    }

    $critical_images = array(
        // Hero background
        '/wp-content/uploads/2022/11/hero-01.jpg',
        // First collection images (above fold on mobile)
        '/wp-content/uploads/2022/11/categorie-02-300x300.jpg',
        '/wp-content/uploads/2022/11/categorie-001-300x300-1.jpg',
        '/wp-content/uploads/2022/11/categorie-003-300x300.jpg',
    );

    foreach ( $critical_images as $path ) {
        $url = esc_url( home_url( $path ) );
        echo '<link rel="preload" as="image" href="' . $url . '">' . "\n";
    }
}

/**
 * Force eager loading for images in the first screen (InfoBox collection images).
 * UAGB generates its own <img> tags that bypass WP's lazy loading counter.
 * This filter catches them in the final HTML output.
 */
add_filter( 'the_content', 'jewelry_fix_lazy_images_for_mobile', 999 );
function jewelry_fix_lazy_images_for_mobile( $content ) {
    // Add decoding=async to images that don't have it
    $content = preg_replace(
        '/<img(?![^>]*\bdecoding\b)/',
        '<img decoding="async" ',
        $content
    );

    return $content;
}

/**
 * Remove lazy loading from small images (icons, decorative elements).
 * These are tiny and should load immediately.
 */
add_filter( 'wp_get_attachment_image_attributes', 'jewelry_optimize_small_images', 10, 3 );
function jewelry_optimize_small_images( $attr, $attachment, $size ) {
    // Remove lazy loading from thumbnails and small images
    if ( isset( $attr['width'] ) && intval( $attr['width'] ) < 100 ) {
        unset( $attr['loading'] );
        $attr['fetchpriority'] = 'low';
    }
    return $attr;
}

/**
 * Add Connection: keep-alive and DNS prefetch hints for performance.
 */
add_action( 'wp_head', 'jewelry_add_performance_hints', 2 );
function jewelry_add_performance_hints() {
    // Preconnect to own domain (helps with sub-resource loading on HTTPS)
    echo '<link rel="preconnect" href="' . esc_url( home_url() ) . '" crossorigin>' . "\n";
    // DNS prefetch
    echo '<link rel="dns-prefetch" href="' . esc_url( home_url() ) . '">' . "\n";
}
